# Generated by Django 4.2.3 on 2023-07-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tppe',
            new_name='type',
        ),
    ]
